server:
  # \u9879\u76EE\u7AEF\u53E3
  port: 8080
  servlet:
    # \u9879\u76EE\u8BBF\u95EE\u8DEF\u5F84
    context-path: /ant
  tomcat:
    # tomcat\u7684uri\u7F16\u7801
    uri-encoding: UTF-8
    # tomcat\u6700\u5927\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4200
    max-threads: 800
    # tomcat\u542F\u52A8\u521D\u59CB\u5316\u7684\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u503C25
    min-spare-threads: 30

spring:
  profiles:
    include: druid,custom
  devtools:
    restart:
      # \u70ED\u90E8\u7F72\u5F00\u5173
      enabled: true
  # aop\u5207\u9762\u914D\u7F6E
  aop:
    auto: true

## \u65E5\u5FD7\u6253\u5370\u914D\u7F6E
logging:
  # \u65E5\u5FD7\u6253\u5370\u7EA7\u522B
  level:
    com.king.ant.*: debug


